models:
  flower:
    weights_path: models/flower_n.pt
    class_names: ["daisy", "wildemoere","flockenblume"]
    confidence_threshold:  0.25
    iou_threshold: 0.5
    max_detections: 30
    margin: 10
    multi_label: false
    multi_label_iou_threshold: 0.7
    augment: false
    image_size: 640
  pollinator:
    weights_path: models/pollinator_m.pt
    class_names: ["honigbiene", "wildbiene","hummel","schwebfliege","fliege"]
    confidence_threshold:  0.25
    iou_threshold: 0.45
    max_detections: 10
    margin: 40
    multi_label: true
    multi_label_iou_threshold: 0.3
    augment: false
    image_size: 640
